/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{js,jsx}",
    ],
    theme: {
        extend: {
            colors: {
                "dark": "#0c1324",
                "card": "#101935",
                "border": "#1E2A4A",
                "primary": "#8B7FFF",
                "surface-tint": "#c0c1ff",
                "surface-container": "#191f31",
                "outline": "#908fa0",
                "secondary-fixed-dim": "#4cd7f6",
                "primary-fixed-dim": "#c0c1ff",
                "secondary-container": "#03b5d3",
                "tertiary-fixed": "#f0dbff",
                "surface-dim": "#0c1324",
                "tertiary-container": "#b76dff",
                "secondary": "#4cd7f6",
                "on-tertiary": "#490080",
                "on-primary-container": "#0d0096",
                "surface-variant": "#2e3447",
                "on-error-container": "#ffdad6",
                "error": "#ffb4ab",
                "secondary-fixed": "#acedff",
                "inverse-on-surface": "#2a3043",
                "tertiary-fixed-dim": "#ddb7ff",
                "primary-container": "#8083ff",
                "error-container": "#93000a",
                "on-tertiary-fixed": "#2c0051",
                "surface-container-lowest": "#070d1f",
                "surface-bright": "#33394c",
                "surface": "#0c1324",
                "tertiary": "#ddb7ff",
                "primary": "#c0c1ff",
                "on-tertiary-fixed-variant": "#6900b3",
                "surface-container-high": "#23293c",
                "on-secondary-container": "#00424e",
                "on-secondary": "#003640",
                "inverse-surface": "#dce1fb",
                "on-error": "#690005",
                "outline-variant": "#464554",
                "on-surface-variant": "#c7c4d7",
                "on-surface": "#dce1fb",
                "on-background": "#dce1fb",
                "on-primary-fixed-variant": "#2f2ebe",
                "background": "#0c1324",
                "on-secondary-fixed-variant": "#004e5c",
                "on-tertiary-container": "#400071",
                "surface-container-highest": "#2e3447",
                "primary-fixed": "#e1e0ff",
                "inverse-primary": "#494bd6",
                "surface-container-low": "#151b2d",
                "on-primary-fixed": "#07006c",
                "on-secondary-fixed": "#001f26",
                "on-primary": "#1000a9"
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px"
            },
            spacing: {
                gutter: "24px",
                "margin-mobile": "16px",
                "margin-desktop": "48px",
                "container-max": "1440px",
                unit: "8px"
            },
            fontFamily: {
                "title-md": ["Sora", "sans-serif"],
                "headline-lg": ["Sora", "sans-serif"],
                "display-xl": ["Sora", "sans-serif"],
                "body-sm": ["Sora", "sans-serif"],
                "body-base": ["Sora", "sans-serif"],
                "label-caps": ["Sora", "sans-serif"],
                "headline-lg-mobile": ["Sora", "sans-serif"]
            },
            fontSize: {
                "title-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
                "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
                "display-xl": ["60px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
                "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
                "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }]
            }
        },
    },
    plugins: [],
}
